### ISSUE TITLE
Folder not getting created on providing format path.

### ISSUE THREAD

**Issue by saumilsdk** [mvtm-dn/cucumber-junit-formatter#9]
Folder not getting created on providing format path.

**Comment by mvtm-dn** [comment]
Am I right that the folder did not create when you run this formatter via something like `-f node_modules/cucumber-junit-formatter[:<output-file>]`, where `output-file` contains the full path to the new file?

**Comment by mvtm-dn** [comment]
Looks like this issue must correspond to JUnit itself.

**Comment by saumilsdk** [comment]
yes @mvtm-dn i have given full path. You can please try providing it and see. And this should be this repo issue i feel and not Junit. Please let me know why it must correspond to JUnit?

**Comment by mvtm-dn** [comment]
Could you please provide an example?

**Comment by saumilsdk** [comment]
Sorry its been long time and i am unable to find where i tried it. You can go ahead and close this as of now.

**Comment by mvtm-dn** [comment]
Am I right you try to use formatter with something like `cucumber-js -f node_modules/cucumber-junit-formatter[:/non-existing-path/to-file/result.json`?

**Comment by saumilsdk** [comment]
I remember using this path in gulpfile.

**Comment by mvtm-dn** [comment]
In fact, formatter received from cucumber not the path to the resulting file but the instance to write log to. So my code neither opened nor created any files and/or folders. My mistake was referring to Junit in one of my previous comments. Indeed you need to open the issue in cucumber repo if the issue is still exists
